import 'package:google_maps_flutter/google_maps_flutter.dart';

/// Ubicación por defecto (Centro de Montevideo, Uruguay)
const LatLng defaultLocation = LatLng(-34.9011, -56.1645); // Montevideo

/// Radio de búsqueda en kilómetros
const double searchRadiusKm = 5.0;

/// Datos simulados de restaurantes mock en Montevideo
const List<Map<String, dynamic>> mockRestaurants = [
  {
    'id': '1',
    'name': 'Pizzería Morosoli',
    'type': 'Italiano',
    'latitude': -34.8950,
    'longitude': -56.1640,
    'rating': 4.7,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Pizzeria+Morosoli',
    'address': 'Avenida Italia 2960, Montevideo',
    'phoneNumber': '+598 2 406 67 67',
    'description': 'Auténtica pizzería italiana con hornos de leña tradicionales',
  },
  {
    'id': '2',
    'name': 'Sushi Tóquio',
    'type': 'Japonés',
    'latitude': -34.9050,
    'longitude': -56.1680,
    'rating': 4.6,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Sushi+Tokio',
    'address': 'Calle Buenos Aires 589, Centro',
    'phoneNumber': '+598 2 900 45 23',
    'description': 'Los mejores rolls de sushi fresco preparados al momento',
  },
  {
    'id': '3',
    'name': 'Chivitería El Corte',
    'type': 'Uruguayo',
    'latitude': -34.9020,
    'longitude': -56.1620,
    'rating': 4.8,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Chiviteria+El+Corte',
    'address': 'Calle 18 de Julio 1512, Centro',
    'phoneNumber': '+598 2 902 22 22',
    'description': 'Famosos chivitos uruguayos preparados con carnes premium',
  },
  {
    'id': '4',
    'name': 'Parrilla Asadito',
    'type': 'Carne',
    'latitude': -34.9100,
    'longitude': -56.1660,
    'rating': 4.9,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Parrilla+Asadito',
    'address': 'Calle Peatonal Sarandí 642, Centro',
    'phoneNumber': '+598 2 915 67 89',
    'description': 'Parrilla de carnes uruguayas de la mejor calidad a las brasas',
  },
  {
    'id': '5',
    'name': 'Burger House Montevideo',
    'type': 'Comida Rápida',
    'latitude': -34.8980,
    'longitude': -56.1700,
    'rating': 4.3,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Burger+House',
    'address': 'Avenida 18 de Julio 2089, Centro',
    'phoneNumber': '+598 2 908 34 56',
    'description': 'Hamburguesas gourmet con ingredientes de la mejor selección',
  },
  {
    'id': '6',
    'name': 'Mariscos Mar del Plata',
    'type': 'Pescados y Mariscos',
    'latitude': -34.9030,
    'longitude': -56.1590,
    'rating': 4.8,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Mariscos+Mar+del+Plata',
    'address': 'Rambla República de Argentina 300, Rambla',
    'phoneNumber': '+598 2 928 12 34',
    'description': 'Pescados y mariscos frescos directo del puerto de Montevideo',
  },
  {
    'id': '7',
    'name': 'Pasta Casera',
    'type': 'Italiano',
    'latitude': -34.9060,
    'longitude': -56.1730,
    'rating': 4.7,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Pasta+Casera',
    'address': 'Calle Mercedes 1387, Centro',
    'phoneNumber': '+598 2 916 89 01',
    'description': 'Pasta fresca hecha diariamente con recetas tradicionales italianas',
  },
  {
    'id': '8',
    'name': 'Wok & Roll Oriental',
    'type': 'Asiático',
    'latitude': -34.8990,
    'longitude': -56.1610,
    'rating': 4.5,
    'imageUrl': 'https://via.placeholder.com/300x200?text=Wok+Roll+Oriental',
    'address': 'Calle Yi 1447, Pocitos',
    'phoneNumber': '+598 2 921 45 67',
    'description': 'Comida oriental fusión con ingredientes frescos y auténticos',
  },
];
